### PR TITLE
+ temp/uploads clearing

### PR DESCRIPTION
**Pull request by dimti**
Clearing temp october directory, where saving uploads resized and sended to s3

### CODE REVIEW

**Comment by alserom** [comment]
I think this does not apply to clear cache functional. Maybe it should be a separate plugin or at least an additional option, which disabled by default, for the clear cache plugin?
Also I not clearly understand what you mean when writing 
> ...and sended to s3

**Comment by dimti** [comment]
That is temp path. But in octobercms today no exists functionality for automatic clearing this dir.

In my case - on the production server, that folder now bigger than 4.1 Gb. With reserve copies - more than 12Gb temporary files.

https://octobercms.com/docs/services/helpers#method-temp-path

This path used in File class: https://github.com/octobercms/library/blob/396f65dc139d0a62b7fb61b767e86aa57a115761/src/Database/Attach/File.php#L973-L973

And, also, used in Resizer (but with is another folder, not `temp/uploads`, it used `temp/resizer`): https://github.com/octobercms/october/blob/f8f5e6e02273c81488542e51be50b5baed7a8af2/modules/system/classes/ImageResizer.php#L341-L341

Temp file need create in `storage/temp/uploads` directory, because that code used this for creating thumb of the image. First file copied from storage (in my case from s3 mini storage - that in-box functionality in octobercms) to local file system in the temp folder: https://github.com/octobercms/library/blob/396f65dc139d0a62b7fb61b767e86aa57a115761/src/Database/Attach/File.php#L656-L656

I have write a ticket into octobercms repository, but i not sure abous that error. On some my server with similar octobercms installation stay is empty `storage/temp/uploads` dir, and i do not why is empty.

I found your plugin as only exists solution (with simple patch) for resolve this situtation with temp/uploads dir.

image

More screenshoots about big size of `storage/temp` dir.

image

image

**Comment by dimti** [comment]
I wrote topic in the octobercms forum https://octobercms.com/forum/post/clearing-temp-folder-on-storage. Maybe i find solution, or this topic need to be moved to octobercms bug-tracker

**Comment by dimti** [comment]
Hmm. temp folder contains not only uploads subfolder. in addition, in temp folder exists media and public subfolder.
And in some cases temp folder used for saving any some files with custom directory structure.
You are rights. That is need deep exploration and do not mix of the clear cache functionality.

OctoberCMS and some users maybe used this folder for many cases.

- Saving uploads, public or media (i do not sure differences)
- Saving artisan console output (stdout redirect to file, without to send info messages to cron daemon)

```
$ du -hsx storage/temp/uploads
664K    storage/temp/uploads
$ du -hsx storage/temp/media/
4.0K    storage/temp/media/
$ ls -la storage/temp -h
total 126M
drwxrwxr-x 5 10ballov www-data 4.0K Oct  3 23:12 .
drwxrwxr-x 7 10ballov www-data 4.0K Jul 15 14:09 ..
-rwxrwxr-x 1 10ballov www-data   22 Jul 15 14:09 .gitignore
drwxrwxrwx 2 10ballov www-data 4.0K Jul 21 12:30 media
drwxrwxr-x 3 10ballov www-data 4.0K Jul 21 12:29 public
-rw-rw-r-- 1 10ballov www-data 126M Oct  5 00:10 scheduledOutput
drwxrwxrwx 2 10ballov www-data 660K Oct  6 18:52 uploads 
$ du -hsx storage/temp/media/
4.0K    storage/temp/media/
$ du -hsx storage/temp/public/
44K     storage/temp/public/
$ ls storage/temp/public/a38/9ec/678/
thumb_a389ec678d31d788ef93023f43c4a4b81595323778_165x165_crop.jpg  thumb_a389ec678d31d788ef93023f43c4a4b81595323778_75x75_crop.jpg
thumb_a389ec678d31d788ef93023f43c4a4b81595323778_300x255_auto.jpg
```

**Pull request closed without merging**
