### PR TITLE
IT locale update

### PR DESCRIPTION
**Pull request by matteotrubini**

### CODE REVIEW

**Comment by alserom** [comment]
Hi @jimibi. In the pr #6, you added a translation into Italian. Do you agree with the changes in this pr? I do not speak Italian, so you guys need to discuss the changes proposed in this commit.

**Comment by matteotrubini** [comment]
I would not seem presumptuous, but @jimibi is from France and I'm Italian, so my corrections should be correct :laughing:

**Comment by jimibi** [comment]
I think matteotrubini's translation is better than mine, my Italian is rather academic, I only lived one year in Italy.

**Comment by alserom** [comment]
Thanks, guys.

**Pull request merged**
