### PR TITLE
Purge thumbs relying on official artisan command

### PR DESCRIPTION
**Pull request by matteotrubini**
Ref. #14 

Superseded code was left as comment per reference, should be deleted
Also README.md should be updated accordingly

### CODE REVIEW

**Comment by alserom** [comment]
I do not see the point in this change. In addition, this changes will cut the current functionality.

**Comment by matteotrubini** [comment]
Just to understand: do you want to simulate the behavior of `php artisan october:util purge thumbs` ?
If yes, isn't simplier to execute that command like it's already done with `cache:clear`?

Ref. https://github.com/octobercms/october/blob/master/modules/system/console/OctoberUtil.php#L257-L295

**Comment by alserom** [comment]
You are right. It will be easier to call an `artisan` command. But the main feature of this part of the widget is that you can only remove some thumbnails. For example, you can remove thumbnails which names end with `_auto.<some_ext>` (Regex: `/^thumb_\w+_auto.*/`) and leave thumbnails which end with `_crop.<some_ext>` (Regex: `/^thumb_\w+_crop.*/`).

**Comment by matteotrubini** [comment]
Got it.

Yesterday I fought two hours before realizing why not all the thumbs were deleted, just because I didn't open the options and I expected a "clear all" behavior. :sweat:

Maybe it would have been better to set `const THUMBNAILS_REGEX = '/^thumb_.*/';` to be more generical, leaving to the user the possibility to specify a more strict selection.

What you think about to add a flag "clear all thumbs" to enable the artisan command instead of regex search? It will be easier for non-developer backend users (like clients and some my colleagues).

**Comment by alserom** [comment]
> Maybe it would have been better to set `const THUMBNAILS_REGEX = '/^thumb_.*/';`  

Yes. It's a good idea. Can you create PR for this? And don't forget to add `1.3.0: Changing default regex for clearing thumbnails` into `version.yaml` please.

> flag "clear all thumbs"  

I think it's unnecessary. Same default regex as in `october:util purge thumbs` command should be enough.

**Pull request closed without merging**
